apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-inference
  template:
    metadata:
      labels:
        app: ml-inference
    spec:
      nodeSelector:
        kubernetes.io/hostname: chiralpair-nano
      runtimeClassName: nvidia  # <-- tells k3s to use NVIDIA runtime
      containers:
        - name: fraud-detection-nano
          image: localhost:5000/fraud-detection-nano:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: 1  # <-- this triggers GPU access
          securityContext:
            seccompProfile:
              type: Unconfined
---              
apiVersion: v1
kind: Service
metadata:
  name: ml-inference-service
spec:
  selector:
    app: ml-inference
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
